name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    services:
      anvil:
        image: ghcr.io/foundry-rs/foundry
        options: --entrypoint anvil --host 0.0.0.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.0-rc1"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
